apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nsv2ogrlr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nsv2ogrlr-go 
  name: nsv2ogrlr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nsv2ogrlr-go 
